version: '3.7'

services:

  hashtopolis:
    image: tomasvanagas/hashtopolis:latest
    volumes:
      - import:/var/www/html/import
      - files:/var/www/html/files
      - inc:/var/www/html/inc
      - mysql:/var/lib/mysql
    ports:
      - "8000:80"

volumes:
  import: {}
  files: {}
  inc: {}
  mysql: {}
